
services:
  atlas-colyseus-server:
    build: ./colyseus-server
    container_name: atlas-world-colyseus-server
    ports:
      - "2567:2567"        # Colyseus WebSocket server
    environment:
      - NODE_ENV=production
      - PORT=2567
    restart: unless-stopped
    networks:
      - atlas-network

volumes:
  atlas_database_data:

networks:
  atlas-network:
    driver: bridge
