name: "Atlas World Development"
runtime:
  path: "/nakama/modules"
  env:
    - "development"
logger:
  level: "debug"
  stdout:
    enabled: true
    level: "debug"
  file:
    enabled: true
    path: "/data/logs"
    level: "info"
session:
  token_expiry_sec: 7200
  refresh_token_expiry_sec: 2592000
socket:
  server_key: "atlas-world-dev-key"
  port: 7350
  address: "0.0.0.0"
  protocol: "websocket"
  ping_period_ms: 8000
  pong_wait_ms: 5000
  ping_backoff_threshold: 10
  message_queue_size: 128
database:
  address: "atlas-database:26257"
  name: "nakama"
  user: "root"
  password: ""
  conn_max_idle: 10
  conn_max_open: 100
  max_open_conns: 100
  max_idle_conns: 10
console:
  port: 7351
  address: "0.0.0.0"
  username: "admin"
  password: "admin"
metrics:
  prometheus_port: 9090
  prometheus_path: "/metrics"
social:
  steam:
    publisher_key: ""
    app_id: ""
  facebook_instant_game:
    app_secret: ""
    validation_timeout_ms: 10000
  facebook:
    app_id: ""
    app_secret: ""
    login_timeout_ms: 10000
storage:
  index_cache:
    max_entries: 10000
  index_rollback:
    max_entries: 1000
  index_ttl_sec: 31536000
leaderboard:
  callback_queue_size: 1024
  callback_queue_workers: 8
match:
  callback_queue_size: 1024
  callback_queue_workers: 8
