//
// THIS FILE HAS BEEN GENERATED AUTOMATICALLY
// DO NOT CHANGE IT MANUALLY UNLESS YOU KNOW WHAT YOU'RE DOING
//
// GENERATED BY colyseus-server/scripts/codegen/gen-csharp-meta.ts FROM contracts/src/meta/types.ts
//

using System.Collections.Generic;

namespace AtlasWorld.Contracts.Meta {

    public enum MatchEventType {
        MOB_KILLED,
        ITEM_PICKED_UP,
        ZONE_ENTERED,
    }

    public sealed class PrimaryStats {
        public double str;
        public double agi;
        public double @int;
        public double vit;
    }

    public sealed class ProfileDoc {
        public int schemaVersion = 1;
        public double level;
        public double xp;
        public double statPoints;
        public PrimaryStats allocated;
    }

    public sealed class InventoryDoc {
        public int schemaVersion = 1;
        public List<InventoryDoc_StackableItem> stackables;
        public List<InventoryDoc_UniqueItem> uniques;
    }

    public sealed class EquipmentDoc {
        public int schemaVersion = 1;
        public EquipmentDoc_Slots slots;
    }

    public sealed class SkillsDoc {
        public int schemaVersion = 1;
        public List<SkillsDoc_UnlockedItem> unlocked;
        public List<string> loadout;
    }

    public sealed class QuestsDoc {
        public int schemaVersion = 1;
        public List<QuestsDoc_ActiveItem> active;
        public List<QuestsDoc_CompletedItem> completed;
    }

    public sealed class MatchEvent {
        public MatchEventType type;
        public string userId;
        public string targetId;
        public double count;
    }

    public sealed class MatchEventBatch {
        public string matchId;
        public double seq;
        public List<MatchEvent> events;
    }

    public sealed class LoadoutSnapshot {
        public int schemaVersion = 1;
        public ProfileDoc profile;
        public LoadoutSnapshot_EquippedItemIds equippedItemIds;
        public List<string> skillLoadout;
        public List<string> activeQuestIds;
    }

    public sealed class InventoryDoc_StackableItem {
        public string itemId;
        public double qty;
    }

    public sealed class InventoryDoc_UniqueItem {
        public string instanceId;
        public string itemId;
    }

    public sealed class EquipmentDoc_Slots {
        public string? weapon;
        public string? armor;
        public string? accessory;
    }

    public sealed class SkillsDoc_UnlockedItem {
        public string skillId;
        public double level;
    }

    public sealed class QuestsDoc_ActiveItem {
        public string questId;
        public double startedAt;
        public Dictionary<string, double> objectives;
    }

    public sealed class QuestsDoc_CompletedItem {
        public string questId;
        public double completedAt;
        public bool claimed;
    }

    public sealed class LoadoutSnapshot_EquippedItemIds {
        public string? weapon;
        public string? armor;
        public string? accessory;
    }

}

