global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'atlas-server'
    static_configs:
      - targets: ['atlas-server:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'atlas-database'
    static_configs:
      - targets: ['atlas-database:5432']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']
