import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { checkMapRender } from "../check_map_render.mjs";
import { SHEETS } from "../../tools/mapforge/render-sheet.mjs";
import { makeTempRepo } from "./helpers/temp-repo.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

test("committed sheets are fresh", () => {
  const { stale, problems } = checkMapRender({ repoRoot: ROOT });
  assert.deepEqual({ stale, problems }, { stale: [], problems: [] });
});

// Integration-style variant (brief §Step 1 alternative): stale a committed
// sheet on disk and assert it is caught.
//
// This used to truncate the REAL, TRACKED sheet and restore it in a `finally`.
// Two successive rewrites of that idiom were both wrong, and the second is the
// one worth remembering:
//   1. `git checkout --` to restore. It can FAIL — any concurrent git process
//      holds this worktree's index.lock, checkout dies with "Unable to create
//      … index.lock: File exists", and the finally block leaves the committed
//      sheet truncated. It also restores to the INDEX, not to what was here,
//      so during a redraw it silently destroys freshly regenerated bytes.
//      (Still present in tools/mapforge/tests/parity.test.mjs; Task 11 disarms
//      it.)
//   2. writeFileSync(original) to restore. Lock-free and state-preserving, and
//      correct while this was the only test file mutating that file. Task 10
//      added a second (scripts/tests/render-lock.test.mjs) and `node --test`
//      runs test FILES in parallel — scripts/package.json's
//      `node --test tests/*.test.mjs` with no --test-concurrency pools at
//      os.availableParallelism(). Two read-modify-restore cycles on one file
//      is a lost-update race whose losing write leaves a DRAWN ARTIFACT
//      truncated for good. Measured: 1 of 4 render-lock runs failed with this
//      file looping alongside it.
// So: no restore idiom is safe, because no test should be writing this file at
// all. `checkMapRender` already takes a repoRoot — the stale sheet goes in a
// sandbox copy, and nothing tracked is written.
test("a stale committed sheet is detected", () => {
  const repo = makeTempRepo({ sheets: SHEETS });
  try {
    const outSvg = join(repo.root, SHEETS.cluster1.outSvg);
    const original = readFileSync(outSvg, "utf8");
    writeFileSync(outSvg, original.slice(0, Math.floor(original.length / 2)));
    const { stale } = checkMapRender({ repoRoot: repo.root });
    assert.ok(stale.includes("cluster1"));
  } finally {
    repo.cleanup();
  }
});
