import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { checkMapRender } from "../check_map_render.mjs";
import { SHEETS } from "../../tools/mapforge/render-sheet.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

test("committed sheets are fresh", () => {
  const { stale, problems } = checkMapRender({ repoRoot: ROOT });
  assert.deepEqual({ stale, problems }, { stale: [], problems: [] });
});

// Integration-style variant (brief §Step 1 alternative): mutate the real
// committed file in place, assert it's caught as stale, then restore.
//
// Restored by REWRITING THE BYTES WE READ, not by `git checkout --`.
// The checkout idiom (still present in tools/mapforge/tests/parity.test.mjs,
// which the plan disarms in Task 11) is wrong here on two counts, both
// reproduced rather than argued:
//   1. It can FAIL. Any concurrent git process holds this worktree's
//      index.lock, `git checkout --` dies with "Unable to create …
//      index.lock: File exists", and the finally block leaves the TRACKED,
//      COMMITTED sheet truncated to half its bytes on disk. Measured: with a
//      lock held, this suite exits 1 and cluster1-world.svg is left at
//      sha256 3bbbee6b… instead of b71586fe… — a change to a drawn artifact
//      caused by a unit test, which is the one thing this plan may not do.
//   2. It restores to the INDEX, not to what was here. During a redraw the
//      sheet is legitimately dirty, and checkout would silently destroy the
//      freshly regenerated bytes — the exact footgun the plan's trap list
//      names for parity.test.mjs.
// `original` is already in memory from the line above, so writing it back is
// lock-free, state-preserving, and strictly more robust. The old comment's
// justification (surviving a mid-test kill) was never achieved by checkout
// either: a killed process runs no finally block at all.
test("a stale committed sheet is detected", () => {
  const outSvg = join(ROOT, SHEETS.cluster1.outSvg);
  const original = readFileSync(outSvg, "utf8");
  try {
    writeFileSync(outSvg, original.slice(0, Math.floor(original.length / 2)));
    const { stale } = checkMapRender({ repoRoot: ROOT });
    assert.ok(stale.includes("cluster1"));
  } finally {
    writeFileSync(outSvg, original);
  }
});
